
package webservices.WebServiceProduto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceProdutoService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:8080/lab141115/WebServiceProduto?wsdl")
public class WebServiceProdutoService
    extends Service
{

    private final static URL WEBSERVICEPRODUTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEPRODUTOSERVICE_EXCEPTION;
    private final static QName WEBSERVICEPRODUTOSERVICE_QNAME = new QName("http://webservices/", "WebServiceProdutoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab141115/WebServiceProduto?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEPRODUTOSERVICE_WSDL_LOCATION = url;
        WEBSERVICEPRODUTOSERVICE_EXCEPTION = e;
    }

    public WebServiceProdutoService() {
        super(__getWsdlLocation(), WEBSERVICEPRODUTOSERVICE_QNAME);
    }

    public WebServiceProdutoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEPRODUTOSERVICE_QNAME, features);
    }

    public WebServiceProdutoService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEPRODUTOSERVICE_QNAME);
    }

    public WebServiceProdutoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEPRODUTOSERVICE_QNAME, features);
    }

    public WebServiceProdutoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceProdutoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceProduto
     */
    @WebEndpoint(name = "WebServiceProdutoPort")
    public WebServiceProduto getWebServiceProdutoPort() {
        return super.getPort(new QName("http://webservices/", "WebServiceProdutoPort"), WebServiceProduto.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceProduto
     */
    @WebEndpoint(name = "WebServiceProdutoPort")
    public WebServiceProduto getWebServiceProdutoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "WebServiceProdutoPort"), WebServiceProduto.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEPRODUTOSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEPRODUTOSERVICE_EXCEPTION;
        }
        return WEBSERVICEPRODUTOSERVICE_WSDL_LOCATION;
    }

}
