
package webservices.WebServiceProduto;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceProduto", targetNamespace = "http://webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceProduto {


    /**
     * 
     * @param preco
     * @param codigoBarra
     * @param descricao
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultadoProdutoCriar", targetNamespace = "")
    @RequestWrapper(localName = "produtoCriar", targetNamespace = "http://webservices/", className = "webservices.WebServiceProduto.ProdutoCriar")
    @ResponseWrapper(localName = "produtoCriarResponse", targetNamespace = "http://webservices/", className = "webservices.WebServiceProduto.ProdutoCriarResponse")
    public String produtoCriar(
        @WebParam(name = "codigoBarra", targetNamespace = "")
        int codigoBarra,
        @WebParam(name = "descricao", targetNamespace = "")
        String descricao,
        @WebParam(name = "preco", targetNamespace = "")
        BigDecimal preco);

    /**
     * 
     * @param idProduto
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultadoProdutoDeletar", targetNamespace = "")
    @RequestWrapper(localName = "produtoExcluir", targetNamespace = "http://webservices/", className = "webservices.WebServiceProduto.ProdutoExcluir")
    @ResponseWrapper(localName = "produtoExcluirResponse", targetNamespace = "http://webservices/", className = "webservices.WebServiceProduto.ProdutoExcluirResponse")
    public String produtoExcluir(
        @WebParam(name = "id_produto", targetNamespace = "")
        int idProduto);

    /**
     * 
     * @param preco
     * @param codigoBarra
     * @param idProduto
     * @param descricao
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultadoProdutoAtualizar", targetNamespace = "")
    @RequestWrapper(localName = "produtoAtualizar", targetNamespace = "http://webservices/", className = "webservices.WebServiceProduto.ProdutoAtualizar")
    @ResponseWrapper(localName = "produtoAtualizarResponse", targetNamespace = "http://webservices/", className = "webservices.WebServiceProduto.ProdutoAtualizarResponse")
    public String produtoAtualizar(
        @WebParam(name = "id_produto", targetNamespace = "")
        int idProduto,
        @WebParam(name = "codigoBarra", targetNamespace = "")
        int codigoBarra,
        @WebParam(name = "descricao", targetNamespace = "")
        String descricao,
        @WebParam(name = "preco", targetNamespace = "")
        BigDecimal preco);

    /**
     * 
     * @param idProduto
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultadoProdutoLer", targetNamespace = "")
    @RequestWrapper(localName = "produtoLer", targetNamespace = "http://webservices/", className = "webservices.WebServiceProduto.ProdutoLer")
    @ResponseWrapper(localName = "produtoLerResponse", targetNamespace = "http://webservices/", className = "webservices.WebServiceProduto.ProdutoLerResponse")
    public String produtoLer(
        @WebParam(name = "id_produto", targetNamespace = "")
        int idProduto);

}
