
package webservices.WebServiceEntrega;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceEntregaService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:8080/lab141115/WebServiceEntrega?wsdl")
public class WebServiceEntregaService
    extends Service
{

    private final static URL WEBSERVICEENTREGASERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEENTREGASERVICE_EXCEPTION;
    private final static QName WEBSERVICEENTREGASERVICE_QNAME = new QName("http://webservices/", "WebServiceEntregaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab141115/WebServiceEntrega?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEENTREGASERVICE_WSDL_LOCATION = url;
        WEBSERVICEENTREGASERVICE_EXCEPTION = e;
    }

    public WebServiceEntregaService() {
        super(__getWsdlLocation(), WEBSERVICEENTREGASERVICE_QNAME);
    }

    public WebServiceEntregaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEENTREGASERVICE_QNAME, features);
    }

    public WebServiceEntregaService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEENTREGASERVICE_QNAME);
    }

    public WebServiceEntregaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEENTREGASERVICE_QNAME, features);
    }

    public WebServiceEntregaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceEntregaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceEntrega
     */
    @WebEndpoint(name = "WebServiceEntregaPort")
    public WebServiceEntrega getWebServiceEntregaPort() {
        return super.getPort(new QName("http://webservices/", "WebServiceEntregaPort"), WebServiceEntrega.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceEntrega
     */
    @WebEndpoint(name = "WebServiceEntregaPort")
    public WebServiceEntrega getWebServiceEntregaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "WebServiceEntregaPort"), WebServiceEntrega.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEENTREGASERVICE_EXCEPTION!= null) {
            throw WEBSERVICEENTREGASERVICE_EXCEPTION;
        }
        return WEBSERVICEENTREGASERVICE_WSDL_LOCATION;
    }

}
