
package webservices.WebServiceVenda;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceVenda", targetNamespace = "http://webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceVenda {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "WebServiceVenda")
    @WebResult(name = "resultadoVenda", targetNamespace = "")
    @RequestWrapper(localName = "WebServiceVenda", targetNamespace = "http://webservices/", className = "webservices.WebServiceVenda.WebServiceVenda_Type")
    @ResponseWrapper(localName = "WebServiceVendaResponse", targetNamespace = "http://webservices/", className = "webservices.WebServiceVenda.WebServiceVendaResponse")
    public String webServiceVenda();

}
