
package webservices.WebServiceVenda;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceVendaService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:8080/lab141115/WebServiceVenda?wsdl")
public class WebServiceVendaService
    extends Service
{

    private final static URL WEBSERVICEVENDASERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEVENDASERVICE_EXCEPTION;
    private final static QName WEBSERVICEVENDASERVICE_QNAME = new QName("http://webservices/", "WebServiceVendaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab141115/WebServiceVenda?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEVENDASERVICE_WSDL_LOCATION = url;
        WEBSERVICEVENDASERVICE_EXCEPTION = e;
    }

    public WebServiceVendaService() {
        super(__getWsdlLocation(), WEBSERVICEVENDASERVICE_QNAME);
    }

    public WebServiceVendaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEVENDASERVICE_QNAME, features);
    }

    public WebServiceVendaService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEVENDASERVICE_QNAME);
    }

    public WebServiceVendaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEVENDASERVICE_QNAME, features);
    }

    public WebServiceVendaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceVendaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceVenda
     */
    @WebEndpoint(name = "WebServiceVendaPort")
    public WebServiceVenda getWebServiceVendaPort() {
        return super.getPort(new QName("http://webservices/", "WebServiceVendaPort"), WebServiceVenda.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceVenda
     */
    @WebEndpoint(name = "WebServiceVendaPort")
    public WebServiceVenda getWebServiceVendaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "WebServiceVendaPort"), WebServiceVenda.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEVENDASERVICE_EXCEPTION!= null) {
            throw WEBSERVICEVENDASERVICE_EXCEPTION;
        }
        return WEBSERVICEVENDASERVICE_WSDL_LOCATION;
    }

}
